# Generated by Django 3.2.12 on 2022-02-07 19:05

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='untitled'),
        ),
    ]
